[2024-10-12T03:50:48.776-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-12T03:50:48.880-0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_dag.prediction_model manual__2024-10-12T08:32:11.781152+00:00 [queued]>
[2024-10-12T03:50:48.898-0500] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_dag.prediction_model manual__2024-10-12T08:32:11.781152+00:00 [queued]>
[2024-10-12T03:50:48.899-0500] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-12T03:50:48.924-0500] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): prediction_model> on 2024-10-12 08:32:11.781152+00:00
[2024-10-12T03:50:48.936-0500] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=281) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-12T03:50:48.941-0500] {standard_task_runner.py:64} INFO - Started process 286 to run task
[2024-10-12T03:50:48.940-0500] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_dag', 'prediction_model', 'manual__2024-10-12T08:32:11.781152+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/train/train_dag.py', '--cfg-path', '/tmp/tmpd4dgq_n1']
[2024-10-12T03:50:48.943-0500] {standard_task_runner.py:91} INFO - Job 29: Subtask prediction_model
[2024-10-12T03:50:49.032-0500] {task_command.py:426} INFO - Running <TaskInstance: train_dag.prediction_model manual__2024-10-12T08:32:11.781152+00:00 [running]> on host 81d4b92477b0
[2024-10-12T03:50:49.220-0500] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_dag' AIRFLOW_CTX_TASK_ID='prediction_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-12T08:32:11.781152+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-12T08:32:11.781152+00:00'
[2024-10-12T03:50:49.222-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-12T03:50:49.228-0500] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv_49hk6ra --python=python
[2024-10-12T03:50:49.231-0500] {process_utils.py:187} INFO - Output:
[2024-10-12T03:50:51.412-0500] {process_utils.py:191} INFO - created virtual environment CPython3.12.4.final.0-64 in 664ms
[2024-10-12T03:50:51.414-0500] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venv_49hk6ra, clear=False, no_vcs_ignore=False, global=False)
[2024-10-12T03:50:51.415-0500] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-12T03:50:51.416-0500] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-12T03:50:51.418-0500] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-12T03:50:51.523-0500] {process_utils.py:183} INFO - Executing cmd: /tmp/venv_49hk6ra/bin/pip install -r /tmp/venv_49hk6ra/requirements.txt
[2024-10-12T03:50:51.525-0500] {process_utils.py:187} INFO - Output:
[2024-10-12T03:50:57.231-0500] {process_utils.py:191} INFO - Collecting joblib (from -r /tmp/venv_49hk6ra/requirements.txt (line 1))
[2024-10-12T03:50:57.236-0500] {process_utils.py:191} INFO -   Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2024-10-12T03:51:03.050-0500] {process_utils.py:191} INFO - Collecting numpy (from -r /tmp/venv_49hk6ra/requirements.txt (line 2))
[2024-10-12T03:51:03.078-0500] {process_utils.py:191} INFO -   Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-12T03:51:06.657-0500] {process_utils.py:191} INFO - Collecting pandas (from -r /tmp/venv_49hk6ra/requirements.txt (line 3))
[2024-10-12T03:51:06.659-0500] {process_utils.py:191} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2024-10-12T03:51:07.065-0500] {process_utils.py:191} INFO - Collecting scikit-learn (from -r /tmp/venv_49hk6ra/requirements.txt (line 4))
[2024-10-12T03:51:07.100-0500] {process_utils.py:191} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2024-10-12T03:51:07.191-0500] {process_utils.py:191} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venv_49hk6ra/requirements.txt (line 3))
[2024-10-12T03:51:07.202-0500] {process_utils.py:191} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-10-12T03:51:07.534-0500] {process_utils.py:191} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venv_49hk6ra/requirements.txt (line 3))
[2024-10-12T03:51:07.537-0500] {process_utils.py:191} INFO -   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2024-10-12T03:51:07.645-0500] {process_utils.py:191} INFO - Collecting tzdata>=2022.7 (from pandas->-r /tmp/venv_49hk6ra/requirements.txt (line 3))
[2024-10-12T03:51:07.648-0500] {process_utils.py:191} INFO -   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-10-12T03:51:08.053-0500] {process_utils.py:191} INFO - Collecting scipy>=1.6.0 (from scikit-learn->-r /tmp/venv_49hk6ra/requirements.txt (line 4))
[2024-10-12T03:51:08.056-0500] {process_utils.py:191} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-12T03:51:08.214-0500] {process_utils.py:191} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn->-r /tmp/venv_49hk6ra/requirements.txt (line 4))
[2024-10-12T03:51:08.219-0500] {process_utils.py:191} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2024-10-12T03:51:08.334-0500] {process_utils.py:191} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venv_49hk6ra/requirements.txt (line 3))
[2024-10-12T03:51:08.341-0500] {process_utils.py:191} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-10-12T03:51:08.386-0500] {process_utils.py:191} INFO - Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
[2024-10-12T03:51:08.436-0500] {process_utils.py:191} INFO - Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
[2024-10-12T03:51:08.586-0500] {process_utils.py:191} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2024-10-12T03:51:10.626-0500] {process_utils.py:191} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2024-10-12T03:51:11.906-0500] {process_utils.py:191} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-10-12T03:51:11.914-0500] {process_utils.py:191} INFO - Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2024-10-12T03:51:11.930-0500] {process_utils.py:191} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2024-10-12T03:51:24.696-0500] {process_utils.py:191} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2024-10-12T03:51:24.758-0500] {process_utils.py:191} INFO - Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2024-10-12T03:51:24.785-0500] {process_utils.py:191} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-10-12T03:51:25.649-0500] {process_utils.py:191} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
[2024-10-12T03:52:42.217-0500] {process_utils.py:191} INFO - Successfully installed joblib-1.4.2 numpy-2.1.2 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.16.0 threadpoolctl-3.5.0 tzdata-2024.2
[2024-10-12T03:52:43.370-0500] {process_utils.py:183} INFO - Executing cmd: /tmp/venv_49hk6ra/bin/python /tmp/venv-callbqt6o0km/script.py /tmp/venv-callbqt6o0km/script.in /tmp/venv-callbqt6o0km/script.out /tmp/venv-callbqt6o0km/string_args.txt /tmp/venv-callbqt6o0km/termination.log
[2024-10-12T03:52:43.376-0500] {process_utils.py:187} INFO - Output:
[2024-10-12T03:52:49.077-0500] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-12T03:52:49.079-0500] {process_utils.py:191} INFO -   File "/tmp/venv-callbqt6o0km/script.py", line 63, in <module>
[2024-10-12T03:52:49.080-0500] {process_utils.py:191} INFO -     res = task_predictionnmodel(*arg_dict["args"], **arg_dict["kwargs"])
[2024-10-12T03:52:49.081-0500] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-12T03:52:49.083-0500] {process_utils.py:191} INFO -   File "/tmp/venv-callbqt6o0km/script.py", line 28, in task_predictionnmodel
[2024-10-12T03:52:49.085-0500] {process_utils.py:191} INFO -     classifier = load("/opt/***/dags/data/model/best_lasso_model.joblib")
[2024-10-12T03:52:49.090-0500] {process_utils.py:191} INFO -                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-12T03:52:49.091-0500] {process_utils.py:191} INFO -   File "/tmp/venv_49hk6ra/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load
[2024-10-12T03:52:49.093-0500] {process_utils.py:191} INFO -     with open(filename, 'rb') as f:
[2024-10-12T03:52:49.093-0500] {process_utils.py:191} INFO -          ^^^^^^^^^^^^^^^^^^^^
[2024-10-12T03:52:49.095-0500] {process_utils.py:191} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/opt/***/dags/data/model/best_lasso_model.joblib'
[2024-10-12T03:52:49.670-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-12T03:52:49.907-0500] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
[Errno 2] No such file or directory: '/opt/***/dags/data/model/best_lasso_model.joblib'
[2024-10-12T03:52:49.951-0500] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=train_dag, task_id=prediction_model, run_id=manual__2024-10-12T08:32:11.781152+00:00, execution_date=20241012T083211, start_date=20241012T085048, end_date=20241012T085249
[2024-10-12T03:52:50.070-0500] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task prediction_model (Process returned non-zero exit status 1.
[Errno 2] No such file or directory: '/opt/***/dags/data/model/best_lasso_model.joblib'; 286)
[2024-10-12T03:52:50.157-0500] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-12T03:52:50.498-0500] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-12T03:52:50.501-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
