[2024-10-12T00:16:20.017-0500] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:16:20.057-0500] {processor.py:830} INFO - Processing file /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py for tasks to queue
[2024-10-12T00:16:20.124-0500] {logging_mixin.py:188} INFO - [2024-10-12T00:16:20.110-0500] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:16:20.492-0500] {logging_mixin.py:188} INFO - [2024-10-12T00:16:20.394-0500] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py", line 8, in <module>
    from common.add_task import task_predictionnmodel
  File "/opt/airflow/dags/common/add_task.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2024-10-12T00:16:20.514-0500] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:16:21.676-0500] {processor.py:183} INFO - Processing /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py took 1.912 seconds
[2024-10-12T00:16:52.404-0500] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:16:52.410-0500] {processor.py:830} INFO - Processing file /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py for tasks to queue
[2024-10-12T00:16:52.423-0500] {logging_mixin.py:188} INFO - [2024-10-12T00:16:52.420-0500] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:16:54.923-0500] {logging_mixin.py:188} INFO - [2024-10-12T00:16:54.909-0500] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py", line 8, in <module>
    from common.add_task import task_predictionnmodel
  File "/opt/airflow/dags/common/add_task.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2024-10-12T00:16:54.928-0500] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:16:55.518-0500] {processor.py:183} INFO - Processing /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py took 3.283 seconds
[2024-10-12T00:17:28.013-0500] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:17:28.042-0500] {processor.py:830} INFO - Processing file /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py for tasks to queue
[2024-10-12T00:17:28.089-0500] {logging_mixin.py:188} INFO - [2024-10-12T00:17:28.088-0500] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:17:28.185-0500] {logging_mixin.py:188} INFO - [2024-10-12T00:17:28.171-0500] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py", line 8, in <module>
    from common.add_task import task_predictionnmodel
  File "/opt/airflow/dags/common/add_task.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2024-10-12T00:17:28.190-0500] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:17:28.219-0500] {processor.py:183} INFO - Processing /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py took 0.271 seconds
[2024-10-12T00:17:58.588-0500] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:17:58.589-0500] {processor.py:830} INFO - Processing file /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py for tasks to queue
[2024-10-12T00:17:58.592-0500] {logging_mixin.py:188} INFO - [2024-10-12T00:17:58.592-0500] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:17:58.629-0500] {logging_mixin.py:188} INFO - [2024-10-12T00:17:58.621-0500] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py", line 8, in <module>
    from common.add_task import task_predictionnmodel
  File "/opt/airflow/dags/common/add_task.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2024-10-12T00:17:58.631-0500] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py
[2024-10-12T00:17:58.655-0500] {processor.py:183} INFO - Processing /opt/airflow/dags/03_third_dag/taskflow_dag_v1-6.py took 0.074 seconds
